/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPatternsRouteImport } from './routes/_app/patterns'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppEvolutionRouteImport } from './routes/_app/evolution'
import { Route as AppAdvisorRouteImport } from './routes/_app/advisor'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPatternsRoute = AppPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEvolutionRoute = AppEvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/advisor': typeof AppAdvisorRoute
  '/evolution': typeof AppEvolutionRoute
  '/home': typeof AppHomeRoute
  '/patterns': typeof AppPatternsRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/advisor': typeof AppAdvisorRoute
  '/evolution': typeof AppEvolutionRoute
  '/home': typeof AppHomeRoute
  '/patterns': typeof AppPatternsRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/advisor': typeof AppAdvisorRoute
  '/_app/evolution': typeof AppEvolutionRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/patterns': typeof AppPatternsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/scan': typeof AppScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/advisor'
    | '/evolution'
    | '/home'
    | '/patterns'
    | '/profile'
    | '/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/advisor'
    | '/evolution'
    | '/home'
    | '/patterns'
    | '/profile'
    | '/scan'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/advisor'
    | '/_app/evolution'
    | '/_app/home'
    | '/_app/patterns'
    | '/_app/profile'
    | '/_app/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/patterns': {
      id: '/_app/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof AppPatternsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/evolution': {
      id: '/_app/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof AppEvolutionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/advisor': {
      id: '/_app/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppEvolutionRoute: typeof AppEvolutionRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPatternsRoute: typeof AppPatternsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScanRoute: typeof AppScanRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdvisorRoute: AppAdvisorRoute,
  AppEvolutionRoute: AppEvolutionRoute,
  AppHomeRoute: AppHomeRoute,
  AppPatternsRoute: AppPatternsRoute,
  AppProfileRoute: AppProfileRoute,
  AppScanRoute: AppScanRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
